# Generated by Django 4.2 on 2024-08-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_trainer_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('T', 'Tierra'), ('F', 'Fuego'), ('E', 'Electrico'), ('A', 'Agua'), ('P', 'Planta')], max_length=30),
        ),
    ]
