# Generated by Django 4.2 on 2024-08-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('F', 'Fuego'), ('L', 'Lagartija'), ('T', 'Tierra'), ('E', 'Electrico'), ('P', 'Planta')], max_length=30),
        ),
    ]
